### ISSUE TITLE
bower install skips screenfull.min.js

### ISSUE THREAD

**Issue by szegheo** [sindresorhus/screenfull.js#90] opened 2015-11-23 12:18 UTC
I'm not familiar with bower.json, so I can't send you a PR, sorry.
screenfull.min.js should be also downloaded when installing with bower

**Comment by SamVerschueren** [comment] 2015-11-23 12:27
You're right, added PR for this.

**Comment by SamVerschueren** [comment] 2015-11-23 12:42
Duplicate of #66

**Closed by SamVerschueren** 2015-11-23 12:42 UTC

**Comment by szegheo** [comment] 2015-11-23 12:50
"Bower packages shouldn't contain minified files."
Interesting.. where is it documented? 9 of 10 bower packages has the minified script, like jQuery and Bootstrap.

**Comment by SamVerschueren** [comment] 2015-11-23 12:54
I guess the idea behind it is to use `gulp`, `grunt` or maybe something else to package your app/website/whatever and to let them minify it for you.

**Comment by szegheo** [comment] 2015-11-23 13:10
Sure, I'm already using Grunt for merge and minify my custom scripts, but my vendors.js is just a merge from many bower packages and its .min.js files, I don't re-uglify them, because each has the minified file. Except this screenfull.js :) That's why I thought minified files should be included. Who/where says that it shouldn't? Can't find...

**Comment by SamVerschueren** [comment] 2015-11-23 13:14
Not sure if it is documented... I'm not the one who made the statement ;).

I actually always use the unminified version and uglify/minify all the libraries myself into one big `libraries.min.js` file.
